@startuml Senha

class GestaoSenha {
    +tipoSenha()
}

interface GerarSenha{
    +gerarSenha()
}

class SenhaNormal{
    +int init_
    +int password
    +int last_password

    +gerarSenha()
}

class SenhaPrioridade {
    +int init
    +int password
    +int last_password

    +gerarSenha()
}

class Historico{
    int ultimaChamadaNormal
    int ultimaChamadaPrioridade

    salvarHistorico()
}

GerarSenha --- SenhaNormal
GerarSenha --- SenhaPrioridade
PasswordGenerator --> GerarSenha 

@enduml
