@startuml Senha

class PasswordManager {
    +createPwd() : PasswordGenerator
}


class NormalAttendance{
    +String attandance_type
    
    +createPwd()
}

class PriorityAttendance{
    +String attandance_type
    
    +createPwd()
}

interface PasswordGenerator{
    +generatePwd()
}

class NormalPwd{
    +String attandance_type
    +int init
    +int password
    +int last_password

    +generatePwd()
}

class PriorityPwd {
    +String attandance_type
    +int init
    +int password
    +int last_password

    +generatePwd()
}

class History{
    int ultimaChamadaNormal
    int ultimaChamadaPrioridade

    saveHistory()
}

PasswordGenerator --- NormalPwd
PasswordGenerator --- PriorityPwd
PasswordManager --- PasswordGenerator
PasswordManager --> NormalAttendance
PasswordManager --> PriorityAttendance

@enduml
